"""empty message

Revision ID: 0f00f7fa9d7a
Revises: 
Create Date: 2023-10-19 10:56:38.546760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f00f7fa9d7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('story_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(), nullable=False),
    sa.Column('child_age', sa.String(), nullable=False),
    sa.Column('child_pronouns', sa.String(), nullable=False),
    sa.Column('child_race', sa.String(), nullable=False),
    sa.Column('child_hairstyle', sa.String(), nullable=False),
    sa.Column('child_location', sa.String(), nullable=False),
    sa.Column('child_clothing', sa.String(), nullable=False),
    sa.Column('child_interests', sa.String(), nullable=False),
    sa.Column('story_setting', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_story_inputs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatgpt_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_response', sa.String(), nullable=False),
    sa.Column('title_text', sa.String(), nullable=True),
    sa.Column('page01_text', sa.String(), nullable=True),
    sa.Column('page02_text', sa.String(), nullable=True),
    sa.Column('page03_text', sa.String(), nullable=True),
    sa.Column('page04_text', sa.String(), nullable=True),
    sa.Column('page05_text', sa.String(), nullable=True),
    sa.Column('page06_text', sa.String(), nullable=True),
    sa.Column('page01_Dalleprompt', sa.String(), nullable=True),
    sa.Column('page02_Dalleprompt', sa.String(), nullable=True),
    sa.Column('page03_Dalleprompt', sa.String(), nullable=True),
    sa.Column('page04_Dalleprompt', sa.String(), nullable=True),
    sa.Column('page05_Dalleprompt', sa.String(), nullable=True),
    sa.Column('page06_Dalleprompt', sa.String(), nullable=True),
    sa.Column('storyinput_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyinput_id'], ['story_inputs.id'], name=op.f('fk_chatgpt_responses_storyinput_id_story_inputs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dalle_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page01_imageurl', sa.String(), nullable=True),
    sa.Column('page02_imageurl', sa.String(), nullable=True),
    sa.Column('page03_imageurl', sa.String(), nullable=True),
    sa.Column('page04_imageurl', sa.String(), nullable=True),
    sa.Column('page05_imageurl', sa.String(), nullable=True),
    sa.Column('page06_imageurl', sa.String(), nullable=True),
    sa.Column('storyinput_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyinput_id'], ['story_inputs.id'], name=op.f('fk_dalle_responses_storyinput_id_story_inputs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dalle_responses')
    op.drop_table('chatgpt_responses')
    op.drop_table('story_inputs')
    op.drop_table('users')
    # ### end Alembic commands ###
