"""empty message

Revision ID: 891410254e8f
Revises: 0f00f7fa9d7a
Create Date: 2023-10-19 11:40:13.419535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891410254e8f'
down_revision = '0f00f7fa9d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatgpt_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page01_dalleprompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page02_dalleprompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page03_dalleprompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page04_dalleprompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page05_dalleprompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page06_dalleprompt', sa.String(), nullable=True))
        batch_op.drop_column('page02_Dalleprompt')
        batch_op.drop_column('page04_Dalleprompt')
        batch_op.drop_column('page05_Dalleprompt')
        batch_op.drop_column('page01_Dalleprompt')
        batch_op.drop_column('page06_Dalleprompt')
        batch_op.drop_column('page03_Dalleprompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatgpt_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page03_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('page06_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('page01_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('page05_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('page04_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('page02_Dalleprompt', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('page06_dalleprompt')
        batch_op.drop_column('page05_dalleprompt')
        batch_op.drop_column('page04_dalleprompt')
        batch_op.drop_column('page03_dalleprompt')
        batch_op.drop_column('page02_dalleprompt')
        batch_op.drop_column('page01_dalleprompt')

    # ### end Alembic commands ###
