"""empty message

Revision ID: dc42aaf95fd0
Revises: d7ea95e76ac7
Create Date: 2023-10-16 16:27:05.951935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc42aaf95fd0'
down_revision = 'd7ea95e76ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_inputs', schema=None) as batch_op:
        batch_op.alter_column('child_age',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_inputs', schema=None) as batch_op:
        batch_op.alter_column('child_age',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
